package generator

import (
	"fmt"
	"strings"
)

const headerV1 = "Code generated by factory generator; DO NOT EDIT."

var validHeaders = []string{
	headerV1,
}

func generateFactoryCodeHeader(strct *Struct) string {
	var builder strings.Builder

	builder.WriteString(fmt.Sprintf("//%s\n", headerV1))
	builder.WriteString(fmt.Sprintf("\n"))
	builder.WriteString(fmt.Sprintf("package %s\n", strct.PackageName))
	builder.WriteString(fmt.Sprintf("\n"))

	return builder.String()
}
