package generator

import (
	"fmt"
	"strings"
)

const headerV1 = "Code generated by go-factory"

var validHeaders = []string{
	headerV1,
}

func generateFactoryCodeHeader(version string, strct *Struct) string {
	var builder strings.Builder

	builder.WriteString(fmt.Sprintf("// %s %s; DO NOT EDIT.\n", headerV1, version))
	builder.WriteString(fmt.Sprintf("\n"))
	builder.WriteString(fmt.Sprintf("package %s\n", strct.PackageName))
	builder.WriteString(fmt.Sprintf("\n"))

	return builder.String()
}
